version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ACTGRP
  - CRTRPGMOD
  - CRTSRVPGM
  - CURLIB
  - DSPSRVPGM
  - ENDPGMEXP
  - ILEDOCS
  - jweirich
  - PGMLVL
  - PRINTTHIS
  - QPRINT
  - QPRPGLESRC
  - QSRVSRC
  - QSYS
  - RELATIVEPATH
  - RPGINC
  - SRCSTMF
  - SRVPGM
  - STRPGMEXP
  - unhex
  - UNHEXED
ignoreWords:
  - QPTYPESRC
  - RPGLEINC
  - varchar
  - RPGLE
  - srcstmt
import: []
